Repository CS4420-Spring19-1/buzzdb, pull requests merged in 2019-04, with the labels that each got.

#9 Add bufferpool, catalog, seqscan and database
  src/database/bufferpool.cpp
  src/database/catalog.cpp
  src/database/database.cpp
  src/database/seqscan.cpp
  src/include/bufferpool.h
  src/include/catalog.h
  src/include/database.h
  src/include/seqscan.h
  src/include/table.h
  src/include/tuple_descriptor.h
Labels: restructure

#14 Restructure update
  src/database/buffer_pool.cpp
  src/database/catalog.cpp
  src/database/database.cpp
  src/database/heap_file.cpp
  src/database/heap_file_encoder.cpp
  src/database/heap_file_iterator.cpp
  src/database/heap_page.cpp
  src/database/lockManager.cpp
  src/database/permissions.cpp
  src/database/predicate.cpp
  src/database/record_id.cpp
  src/database/seq_scan.cpp
  src/database/transaction_id.cpp
  src/database/tuple.cpp
  src/database/tuple_desc.cpp
  src/database/utility.cpp
  src/include/buffer_pool.h
  src/include/catalog.h
  src/include/database.h
  src/include/db_file.h
  src/include/heap_file.h
  src/include/heap_file_encoder.h
  src/include/heap_file_iterator.h
  src/include/heap_page.h
  src/include/iterator.h
  src/include/page.h
  src/include/permissions.h
  src/include/predicate.h
  src/include/random_access_file.h
  src/include/seq_scan.h
  src/include/transaction_id.h
  src/include/tuple.h
  src/include/tuple_desc.h
  src/include/utility.h
Labels: restructure

#20 Implementation fixes
  src/database/buffer_pool.cpp
  src/database/db_exception.cpp
  src/database/db_file.cpp
  src/database/db_file_iterator.cpp
  src/database/db_iterator.cpp
  src/database/field.cpp
  src/database/heap_page.cpp
  src/database/heap_page_id.cpp
  src/database/integer_field.cpp
  src/database/no_such_element_exception.cpp
  src/database/page.cpp
  src/database/page_id.cpp
  src/database/predicate.cpp
  src/database/record_id.cpp
  src/database/seq_scan.cpp
  src/database/string_field.cpp
  src/database/transaction.cpp
  src/database/transaction_aborted_exception.cpp
  src/database/transaction_id.cpp
  src/database/tuple.cpp
  src/database/tuple_desc.cpp
  src/database/type.cpp
  src/include/buffer_pool.h
  src/include/db_exception.h
  src/include/db_file.h
  src/include/db_file_iterator.h
  src/include/db_iterator.h
  src/include/field.h
  src/include/field_type.h
  src/include/heap_file_encoder.h
  src/include/heap_page.h
  src/include/heap_page_id.h
  src/include/integer_field.h
  src/include/no_such_element_exception.h
  src/include/page.h
  src/include/page_id.h
  src/include/record_id.h
  src/include/seq_scan.h
  src/include/string_field.h
  src/include/transaction.h
  src/include/transaction_aborted_exception.h
  src/include/transaction_id.h
  src/include/tuple.h
  src/include/tuple_desc.h
  src/include/type.h
  test/CMakeLists.txt
  test/HeapPageIdTest.cpp
  test/RecordIdTest.cpp
  test/benchmark.cpp
  test/heap_page_id_unit_test.cpp
  test/heap_page_read_test.cpp
  test/record_id_unit_test.cpp
  test/setup_db_test.cpp
  test/tuple_desc_test.cpp
  test/tuple_test.cpp
Labels: bug, restructure

#23 Update README.md
  README.md
Labels: invalid

#24 Implementation updates
  src/database/heap_page_id.cpp
  src/database/record_id.cpp
  src/database/tuple.cpp
  src/database/tuple_desc.cpp
  src/include/tuple.h
  src/include/tuple_desc.h
  test/heap_page_id_unit_test.cpp
  test/record_id_unit_test.cpp
Labels: enhancement, restructure

#27 Add Lab 4 files
  src/database/int_histogram.cpp
  src/database/string_histogram.cpp
  src/include/int_histogram.h
  src/include/string_histogram.h
Labels: enhancement
